.catalog:
  name: Skydns
  version: 2.5.3-rancher1
  description: |
    (Experimental) Skydns service.
  minimum_rancher_version: v1.11.0
  maintainer: "Raul Sanchez <rawmind@gmail.com>"
  uuid: skydns-0
  questions:
    - variable: "skydns_scale"
      description: "Skydns scale to deploy"
      label: "Skydns scale:"
      required: true
      default: "3"
      type: "int"
    - variable: "skydns_etcd"
      description: "Etcd url to connect to"
      label: "Etcd url:"
      required: true
      default: "http://etcd:2379"
      type: "string"
    - variable: "skydns_addr"
      description: "Skydns address to bind."
      label: "Skydns bind:"
      required: true
      default: "0.0.0.0:53" 
      type: "string"
    - variable: "skydns_domain"
      description: "Skydns domain"
      label: "Skydns domain:"
      required: true
      default: "dev.local"
      type: "string"
    - variable: "skydns_nameservers"
      description: "Skydns nameservers forwarders."
      label: "Skydns nameservers:"
      required: true
      default: "8.8.8.8:53,8.8.4.4:53"
      type: "string"
    - variable: "skydns_path_prefix"
      description: "Skydns path prefix"
      label: "Skydns path prefix:"
      required: true
      default: "skydns"
      type: "string"
    - variable: "skydns_ndots"
      description: "skydns_ndots"
      label: "skydns_ndots:"
      required: true
      default: 5
      type: "string"
skydns:
  scale: ${skydns_scale}
  retain_ip: true
  health_check:
    port: 53
    interval: 5000
    unhealthy_threshold: 3
    request_line: ''
    healthy_threshold: 2
    response_timeout: 5000
